name: dark_social
description: "Dark Social All-In-One Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.0
  audio_session: ^0.1.21
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
